eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
spring:
  zipkin:
    base-url: http://localhost:9411
  kafka:
    bootstrap-servers: broker:29092