eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
server:
  port: 0

spring:
  application:
    name: notification-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
    integration:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spirng:
          json:
            type:
              mapping: event:com.programmingmsa.notificationservice.OrderPlacedEvent
      group-id: notificationId