spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory_service
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: inventory-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

# Actuator Prometheus Endpoint
management:
  endpoints:
    web:
      exposure:
        include: prometheus