server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm
    zipkin:
      base-url: http://localhost:9411