spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
      host: mongo
      port: 27017
      database: product-service
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
server:
  port: 8080