spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
  application:
    name: product-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

server:
  port: 0

# Actuator Prometheus Endpoint
management:
  endpoints:
    web:
      exposure:
        include: prometheus